### ISSUE TITLE
Discovery: Open Source starting point for Data Catalogue kernel

### ISSUE THREAD

**Issue by CharlesAHunt** [Headstorm/dexter#3]
We need to determine a starting point for creating a data catalogue

- A list of options exist to build from

**Comment by Agelb** [comment]
Some similar tools:

- [Apache Atlas](https://atlas.apache.org/index.html#/)
- [Magda](https://magda.io/)
- [CKAN](https://ckan.org/)
- [Knowledge-Repo](https://github.com/airbnb/knowledge-repo)
- [DataHub](https://github.com/linkedin/datahub)

Of these options, Atlas, Magda, and DataHub have features and purposes that are the most similar to this project. In particular, Atlas' tag propogation, lineage, and access controls, Magda's federated searchability, and DataHub's search/query features. 

Atlas and DataHub both use graph databases for relationships between entities (datasets, ETL operations, users, etc). Atlas uses JanusDB by default but has a pluggable graph backend, while DataHub uses Neo4j. DataHub also uses several additional tools for search and indexing. Magda uses Postgres to store dataset info, and Elasticsearch for indexing and query.

My recommendation is to spend time experimenting with Atlas. It's extensible type system allows ETL processes to be modeled, and any arbitrary properties can be added and modeled.

**Comment by Agelb** [comment]
To start with, let's use neo4j for a graph backend.  The graph model will let us query on propogation and relaitonships, which is a hugely valuable feature from Atlas, and The cypher queries are simpler and more readable for the initial pass. In addition, let's start with a simple data model of Template, Attribute, Instance, and Attribute Value.
