### ISSUE TITLE
Discovery: Essential elements we need for a data catalogue

### ISSUE THREAD

**Issue by CharlesAHunt** [Headstorm/dexter#7]
- List of essential elements for a data catalogue

**Comment by Agelb** [comment]
The essential elements we need for a data catalog are:

1. searchability
2. taggability
3. usability

## searchability
The catalog needs to answer the following kinds of questions:
* Which data sources are in S3? RDS? Postgres?
* Where is the dataset location? Specifically, hostnames, connection strings, s3 locations, blob storage information, etc
* What data is in the dataset? For example, "show me all datasets with a column named `user_id`"

## taggability
* Must support user defined tags (PII, Deprecated, Unverified, etc)
* Must be able to attach tags to essentially any entity. 
* Must be able to find any related entity of a tagged entity. For example, Column `firstname` is tagged as PII. Find all datasets using this column, including any process or derived data sets

## usability
One of the most challenging aspects of this is to communicate to the end-users how the dynamic type system works. Creating objects and building search queries needs to be clear to the end-user; they need to be able to navigate these graphs comfortably to get the full value of the catalog.
